# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB
  pod "PreviewTransition"
  pod 'Moya', '~> 11.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SwiftyJSON', '~> 4.0'
  


  target 'MovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
